#!/bin/bash

CONTAINER=hobbytaste_mongodb

trap './cleanup $CONTAINER' EXIT
if ! sudo docker start $CONTAINER 2>/dev/null
then
	sudo docker pull mongo
        sudo docker run -dp 27017:27017 --name $CONTAINER mongo
fi
NODE_APP_INSTANCE=secrets NODE_ENV=development ts-node-dev --project server/tsconfig.json --clear --respawn --transpileOnly ./server/app.ts
