#!/bin/bash

CONTAINER=hobbytaste_mongodb

echo "Setting up DB..."
trap './tasks/cleanup $CONTAINER' EXIT
if ! docker start $CONTAINER 2>/dev/null
then
	docker pull mongo >/dev/null
        docker run -dp 27017:27017 --name $CONTAINER mongo >/dev/null
	echo DB container $CONTAINER
fi
echo "Running server..."
NODE_APP_INSTANCE=secrets NODE_ENV=development ts-node-dev --project server/tsconfig.json --clear --respawn --transpileOnly ./server/app.ts
