#!/bin/bash

CONTAINER=hobbytaste_mongodb

trap './tasks/cleanup $CONTAINER' EXIT

echo "Loading fixtures..."
node tasks/fixtures.js >/dev/null
echo "Running server..."
NODE_APP_INSTANCE=secrets NODE_ENV=development ts-node-dev --project server/tsconfig.json --clear --respawn --transpileOnly ./server/app.ts
